// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest  = require("bs-jest/lib/js/src/jest.js");
var Time  = require("../src/time.js");
var Curry = require("bs-platform/lib/js/curry.js");

describe("Expect", (function () {
        return Jest.test("toBe", (function () {
                      return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](3));
                    }));
      }));

describe("Instant", (function () {
        Jest.test("instant", (function () {
                return Curry._2(Jest.Expect[/* Operators */23][/* == */0], Jest.Expect[/* expect */0](Time.Instant[/* make */0](/* () */0)), /* () */0);
              }));
        return Jest.test("instant round trip", (function () {
                      return Curry._2(Jest.Expect[/* Operators */23][/* == */0], Jest.Expect[/* expect */0](Time.decodedInstant), /* () */0);
                    }));
      }));

/*  Not a pure module */
