// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var TransitJs = require("transit-js");

function string_of_format(t) {
  if (t !== 0) {
    return "json-verbose";
  } else {
    return "json";
  }
}

function reader($staropt$star, options) {
  var format = $staropt$star ? $staropt$star[0] : /* Json */0;
  var readerType = string_of_format(format);
  return TransitJs.reader(readerType, options);
}

function writer($staropt$star, options) {
  var format = $staropt$star ? $staropt$star[0] : /* Json */0;
  var writerType = string_of_format(format);
  return TransitJs.writer(writerType, {
              handlers: options
            });
}

exports.reader = reader;
exports.writer = writer;
/* transit-js Not a pure module */
